# Generated by Django 3.0.7 on 2020-06-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('key_1', models.CharField(blank=True, default='', max_length=100)),
                ('key_2', models.CharField(blank=True, default='', max_length=100)),
                ('key_3', models.CharField(blank=True, default='', max_length=100)),
                ('key_4', models.CharField(blank=True, default='', max_length=100)),
                ('key_5', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
