# Generated by Django 3.0.7 on 2020-06-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='key_1',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='key_2',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='key_3',
            new_name='hair',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='key_4',
            new_name='physic',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='key_5',
            new_name='race',
        ),
    ]
