# Generated by Django 3.0.7 on 2020-06-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20200609_1338'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='Image',
        ),
    ]
